### ISSUE TITLE
Translations are not reflected again from transifex

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#103]
Hi @m-kuhn ,

I translated addition ones to Japanese language in the last month. However, my translations are not reflected yet again.

In transifex, I can see French version also completed translations. But in the website of French is also the same with Japanese version.

I found the following article of "geotagging" has this issue.

- the page of Japanese version
https://qfield.org/docs/ja/prepare/add-1-n-pictures.html#geotagging

- the page of French version
https://qfield.org/docs/fr/prepare/add-1-n-pictures.html#geotagging

**Comment by lucienicolier** [comment]
Hi @JinIgarashi it should be fixed now in this pull request
