### ISSUE TITLE
QFieldSync plugin in dire need of updates to its screenshots

### ISSUE THREAD

**Issue by nirvn** [opengisch/QField-docs#118]
Visiting the QFieldSync documentation page (https://qfield.org/docs/synchronise/qfieldsync.html), I noticed it direly needs a refresh of its captured screens :)

**Comment by lucienicolier** [comment]
@nirvn don't you think it would better to do it when we have QFieldCould running for everyone?

**Comment by nirvn** [comment]
Not sure. The windows 95 look is not great to begin with, and the UI elements, such as the toolbar, are already outdated.
