### ISSUE TITLE
Translation - polish

### ISSUE THREAD

**Issue by martaksx** [opengisch/QField-docs#125]
Hello!
I would like to translate the documentation to polish. I've already created my account at transifex.com as recommended, but on when I click the "Join team" button (when I'm here https://www.transifex.com/opengisch/qfield-documentation/) there is no Polish to choose. Can you please make it active? I would really like to give my contribution to this project :)

**Comment by m-kuhn** [comment]
Thanks a lot for your interest !
Your request was just accepted, please let me know if you have any further questions.
