### ISSUE TITLE
Create a recipes section

### ISSUE THREAD

**Issue by Marwe** [opengisch/QField-docs#157]
I would love to see a recipe section, where small to medium documentations can be created for specific tasks.
A recipe would follow a certain structure like:

* title: target to be achieved, 
* yield
* prerequisites/ingredients (data, settings, other recipes)
* how long to prepare
* procedures
* review, yield

and could be from small (how to add a photo attribute) to medium complexity (how to set up a project for a certain task, sync workflow, ...).

**Comment by marioba** [comment]
Thanks for this interesting suggestion. 
We are currently working on reorganizing the QField documentation.

Could you please prepare a recipe as an example?

**Comment by jonnyforestGIS** [comment]
@marioba this is not the new section https://docs.qfield.org/how-to/ ? If yes, this can be close. Cheers

**Comment by Marwe** [comment]
Since I did not yet create such a receipt, HowTo is fine (can be structured like a receipe), so close it here. Someone did such a thing here (in German): https://farmwissen.de/praxisleitfaden/show/index.php?prax_id=19
