### ISSUE TITLE
Error 6: Only single band dataset supported for non Byte datatype

### ISSUE THREAD

**Issue by Heryx** [opengisch/QField-docs#16]
Hi, I try to convert a tif image in gpkg, but I have this type of problem:

`Error 6: Only single band dataset supported for non Byte datatype`

This are the information of the raster:

`

Originale | ruotate4_5lwp_bp_7 16
-- | --
Nome | ruotate4_5lwp_bp_7 16
Sorgente | C:/Users/Giuse/Desktop/GPR-JOBS/17 PAESTUM/Paestum/Elaborazioni/Pae_NO1/jpg/ruotate4_5lwp_bp_7 16.7-19.5ns 16.5-16.6m.tif
Sorgente dati | gdal
SR | EPSG:6708 - RDN2008 / UTM zone 33N (N-E) - Proiettato
Estensione | 500322.6536733710090630,4474954.9309797398746014 : 500337.4928733709966764,4474975.5409797402098775
Unità | metri
Larghezza | 432
Altezza | 600
Tipo di dato | UInt16 - Intero senza segno di 16 bit
Descrizione Driver GDAL | GTiff
Metadata Driver GDAL | GeoTIFF
Descrizione dell'insieme di dati | C:/Users/Giuse/Desktop/GPR-JOBS/17 PAESTUM/Paestum/Elaborazioni/Pae_NO1/jpg/ruotate4_5lwp_bp_7 16.7-19.5ns 16.5-16.6m.tif
Compressione |  
Banda 1 | STATISTICS_MAXIMUM=65535 STATISTICS_MEAN=26551.765621142 STATISTICS_MINIMUM=1028 STATISTICS_STDDEV=28558.731952742
Banda 2 | STATISTICS_MAXIMUM=65535 STATISTICS_MEAN=30986.322434414 STATISTICS_MINIMUM=0 STATISTICS_STDDEV=22724.011120265
Banda 3 | STATISTICS_MAXIMUM=65535 STATISTICS_MEAN=40274.896350309 STATISTICS_MINIMUM=0 STATISTICS_STDDEV=24815.104437129
Banda 4 | STATISTICS_MAXIMUM=65535 STATISTICS_MEAN=60531.635358796 STATISTICS_MINIMUM=0 STATISTICS_STDDEV=17402.92630647
Maggiori informazioni | TIFFTAG_DOCUMENTNAME=C:\slice\v7.0\temp.tif TIFFTAG_SOFTWARE=ImageMagick 6.3.9 03/11/08 Q16 http://www.imagemagick.org
Dimensioni | X: 432 Y:.600 Bande: 4
Origine | 500323,4.47498e+6
Dimensione pixel | 0.03435,-0.03435
`

**Comment by m-kuhn** [comment]
How do you convert it?

**Comment by Heryx** [comment]
I would like to convert it to gpkg

**Comment by m-kuhn** [comment]
That is quite clear from the text.
What do you do before you get the error?

**Comment by Heryx** [comment]
I wrote this string of code in the shell:

`gdal_translate --config OGR_SQLITE_SYNCHRONOUS OFF -co  APPEND_SUBDATASET=YES -co TILE_FORMAT=PNG_JPEG -a_srs EPSG:21781 -of GPKG raster.tif raster.gpkg
gdaladdo --config OGR_SQLITE_SYNCHRONOUS OFF -r AVERAGE raster.gpkg 2 4 8 16 32 64 128 256`

replacing the name raster.tif/gpkg with the name of my raster, and replacing the EPSG:21781 wiht 6708.

**Comment by m-kuhn** [comment]
Maybe one of these links help?

 * https://gis.stackexchange.com/questions/244073/unable-to-convert-3-band-spacenet-dataset-geotiff-image-to-either-jpg-or-png-wit
 * https://gis.stackexchange.com/questions/33407/how-to-use-gdal-to-convert-int16-data-to-byte

**Comment by mbernasocchi** [comment]
is this supposed to be in the QField docs issues? isn't it more a QField thing? please reopen if still relevant at all @Heryx and @m-kuhn
