### ISSUE TITLE
Wrong links in docs

### ISSUE THREAD

**Issue by thymaro** [opengisch/QField-docs#163]
The links on the pages ("authentication" is just an example, it's the same on all the documentation  pages)

    https://docs.qfield.org/how-to/authentication/

to "edit this page" (pencil icon in upper right corner) point to

    https://github.com/opengisch/qfield-docs/tree/master/docs/how-to/authentication.en.md

but they lead to a 404 page. The correct links have two differences, "blob" and "documentation"

    https://github.com/opengisch/QField-docs/blob/master/documentation/how-to/authentication.en.md

**Comment by marioba** [comment]
Hi @thymaro 
thanks for reporting this. I'll fix it immediately.
Cheers
