### ISSUE TITLE
Please restore existing translation work in transifex

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#173]
I am a translator to Japanese language in Transifex.
I am really excited to see your new documentation website. Thank you for developing new site. However, I found most of existing translations in Transifex disappeared now. 
I think most of strings are not changed. Could you restore some of existing translations to new documentation?
I don’t want to repeat the previous work again. Also, I don’t have any more time to do the same things again.
I believe other languages translators also feel the same with me.

**Comment by marioba** [comment]
Hi @JinIgarashi 
thank you for reporting this and thank you very much for your translation work.

The structure of the documentation has changed as well as the format of the files. 
Where, according to Transifex, there is a 100% match between a sentence in the previous documentation and the current documentation, the old translation has been directly applied. 
Unfortunately though, as you noticed, there are many cases where a sentence is not considered a 100% match by Transifex, and no translation is applied.

I'm trying to figure out if there is anything that can technically be done on Transifex to improve this situation. I'm open to suggestions...

For info, the old documentation is still visible here https://qfield.org/docs/

**Comment by JinIgarashi** [comment]
@marioba Thank you. That is good news the old documentation is still remaining. At least it can be helpful.
