### ISSUE TITLE
WMS cache server

### ISSUE THREAD

**Issue by DLucasG** [opengisch/QField-docs#24]
I am trying to load a wms server and everything is correct. But when I'm in the field (I do not have internet) the wms is not saved. How can I make it stay in memory?

**Comment by m-kuhn** [comment]
Have a look at the [base map](https://www.qfield.org/docs/qfieldsync/index.html#base-map-configuration) functionality.
For further requests, please use [one of the support channels](https://www.qfield.org/docs/development/index.html#support).
