### ISSUE TITLE
Add the gridshift file type

### ISSUE THREAD

**Issue by EricBap** [opengisch/QField-docs#259]
Please add the filetypes for the supported vertical gridshift files in the howto: 

I my case this was a *.gtx  
 
https://docs.qfield.org/how-to/gnss/

**Comment by m-kuhn** [comment]
Thank you for helping with more information here :heart: 

Was it working as expected?

Did you know you can add information by clicking the pencil at the top of the page (as a proposal, you cannot do any damage directly)?

**Comment by m-kuhn** [comment]
Hi @EricBap can you give us a feedback here, so the documentation can be improved accordingly?
Thank you

**Comment by m-kuhn** [comment]
@nirvn you have added this iirc?

**Comment by nirvn** [comment]
Ya.

**Comment by EricBap** [comment]
Yes
