### ISSUE TITLE
Don't deploy "prod" doc from other branches than master

### ISSUE THREAD

**Issue by marioba** [opengisch/QField-docs#26]
Currently Travis will deploys the doc for each push even in secondary branches. 
A better solution can be to deploy the doc from other branches to a different url.

**Comment by m-kuhn** [comment]
So, this https://github.com/opengisch/QField-docs/blob/master/scripts/ci/deploy-docs.sh#L8 doesn't work?

**Comment by marioba** [comment]
@m-kuhn apparently not. In fact your pull request "simons use case" is already showed on the main doc page...

**Comment by marioba** [comment]
It worked on the `continuous-integration/travis-ci/push` but not on the `continuous-integration/travis-ci/pr` check

**Comment by m-kuhn** [comment]
Fixed in c3c1b420dbdb2de06e333ff3f7accd69476c86bc
