### ISSUE TITLE
Itineraries in QField are broken, fix QField or fix doc

### ISSUE THREAD

**Issue by nirvn** [opengisch/QField-docs#287]
Itineraries have been broken in QField since forever (never knew it was a thing until I stumbled on https://docs.qfield.org/how-to/itinerary/).

We should either remove the documentation page, or fix the little-known feature in QField (and add a proper UI in qfieldsync).

**Comment by m-kuhn** [comment]
If nobody ever complained about it I would rather remove it to keep the code cleaner.

**Comment by nirvn** [comment]
Big +1
