### ISSUE TITLE
i18n for home page

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#346]
There is still English in `Home` page of the documentation even other language is selected.

![image](https://github.com/opengisch/QField-docs/assets/2639701/c84ef2df-077f-46c9-ac98-c2920674501d)

Looks like strings are hard coded in the template of `home.html`. It would be better if home page can also be translated.

https://github.com/opengisch/QField-docs/blob/649911b210b11d3958bb4a66fa51b97ad0c9d3f7/theme_overrides/home.html#L37-L60

**Comment by m-kuhn** [comment]
Thank you for raising this.
@why-not-try-calmer do you have an idea how to improve the situation?

**Comment by JinIgarashi** [comment]
@m-kuhn I created PR #348 which can partially fix this issue (not address for all). However, I am still not sure how we can translate `site_name` and `description` in `home.html`.

**Comment by why-not-try-calmer** [comment]
> Thank you for raising this. @why-not-try-calmer do you have an idea how to improve the situation?

There's a pending PR (context: https://github.com/opengisch/signalo/issues/78#issuecomment-1536056490) upstream that should improve the situation. As it seems to be taking more time than anticipated, it might be interesting to look into the fork offering the custom `site_description` patch.

**Comment by JinIgarashi** [comment]
@m-kuhn Thank you for merging the PR! Should we reopen this issue since the PR only fixed the issue partially?

**Comment by m-kuhn** [comment]
@JinIgarashi please reopen the issue or create a new one as you see better fit.

**Comment by JinIgarashi** [comment]
I can’t see reopen button in the issue!
