### ISSUE TITLE
Image is not shown when a link is pasted to social media 

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#353]
Paste a link like “ https://docs.qfield.org/ja/success-stories/rwanda-rural-water/” to social media.

now a card is shown, but image is still not shown. Maybe og:image setting has problems.

also, description is not shown. 

<img width="820" alt="image" src="https://github.com/opengisch/QField-docs/assets/2639701/f0a3ade7-a8ab-439a-bc90-5a4c870aff82">

**Comment by m-kuhn** [comment]
![image](https://github.com/opengisch/QField-docs/assets/588407/b5cae29c-24c6-4c78-8223-56fcadc386a9)

Maybe we need `/assets` instead of `assets`?

**Comment by JinIgarashi** [comment]
![image](https://github.com/opengisch/QField-docs/assets/2639701/1d1fbd06-78be-4245-b71f-f99ef20ea9dd)

I just tested in whatsapp, it’s shown well.

**Comment by JinIgarashi** [comment]
Maybe this can be an issue? We need a larger image for this card in twitter? Current image is just small logo

https://github.com/opengisch/QField-docs/blob/2142805ac483edcf22527d61646692a46edb3a88/theme_overrides/main.html#L27

**Comment by JinIgarashi** [comment]
Maybe we need a specific image for the link. See the below spec. I put svg link. And twitter doesn’t support svg for it

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

also we may need twitter:description as well.

@m-kuhn could you make a nice image for meta tag?

**Comment by JinIgarashi** [comment]
@m-kuhn Maybe we should try this MkDocs plug-in for social image.

https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/

**Comment by m-kuhn** [comment]
![qfield_logo](https://github.com/opengisch/QField-docs/assets/588407/fe154cbe-8250-492b-b22d-fe2f59df494d)

Converted the svg to png using inkscape, you could copy that to documentation/assets/images

**Comment by JinIgarashi** [comment]
thanks, but I think I found a solution with social plugin. It can generate quite nice images dynamically. check #354
