### ISSUE TITLE
Finnish translation of documentation not on the website

### ISSUE THREAD

**Issue by rekjuh** [opengisch/QField-docs#402]
Hi,

there is a Finnish translation page on Transifex for the documentation. There are strings translated to Finnish but they are not on the documentation page.

**Comment by m-kuhn** [comment]
Thank you for reporting, this should be fixed in the next minutes

**Comment by m-kuhn** [comment]
Here we go: https://docs.qfield.org/fi/

The main page is not yet translated, if you could help with that by editing it here, that would be great: 

Editable link: https://github.com/opengisch/QField-docs/edit/master/mkdocs.yml#L210-L213

https://github.com/opengisch/QField-docs/blob/99fa6b21cb122058535be96ca762e3b26a4ec625/mkdocs.yml#L210-L213
