### ISSUE TITLE
Update documentation translation

### ISSUE THREAD

**Issue by ValPinnaSardinia** [opengisch/QField-docs#458]
HI,

we are currently working to achieve 100% Italian translation of your documentation.
However, I noticed that the site shows a rather old version of the translated documentation.
Might it be possible to update it to the latest version on TX?. It would be very useful to see our work online to check consistency on translation, errors and missing strings.

Many thanks

Val

**Comment by ValPinnaSardinia** [comment]
Just to update, thanks to italian community of QGIS translator, we achive the 100%. It would be very useful to see the result of our work online to check consistency and fix issues.

**Comment by m-kuhn** [comment]
Hi, I just triggered an update, it looks like the workflow was broken. Can you check again?

**Comment by PCA-Geodata** [comment]
Hi. Yes, I confirm. New version is online. Thanks a lot
