### ISSUE TITLE
Possible adjustment in Plugins how-to

### ISSUE THREAD

**Issue by gacarrillor** [opengisch/QField-docs#464]
I'm not a native English speaker, but could this:

https://github.com/opengisch/QField-docs/blob/3636704c789c2bd39fd994e0839efce8dcbd200f/documentation/how-to/plugins.en.md?plain=1#L74

be:

`The `iface.mapCanvas()` function provides access to the map canvas item and its properties,`

?

**Comment by suricactus** [comment]
Thanks for spotting this. Can you please open a PR with the suggested changes?
