### ISSUE TITLE
Supported data formats

### ISSUE THREAD

**Issue by lucienicolier** [opengisch/QField-docs#51]
https://qfield.org/docs/project-management/dataformat.html

Is the note on the table about Postgis "Ssl support not yet implemented." still right?

**Comment by m-kuhn** [comment]
Let's remove it. I did not check, but libpq.so is linked against libssl_1_1.so, so that should be good.

**Comment by m-kuhn** [comment]
@lucienicolier did you already change it?

A super cool feature of github is that you can create a pull request where you remove the note and in the commit message (or the pull request) you write `Fix #51` and it will automatically close this issue when it's merged.

**Comment by lucienicolier** [comment]
@m-kuhn I changed on my branch "new_structure" do you want me to to it on the master? In the good way?

**Comment by m-kuhn** [comment]
If you do it in your branch you could add it to the commit message.

But let's try it "the good way" on master as an exercise :)
