### ISSUE TITLE
Document itineraries

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/QField-docs#61]
this wiki page should go in the doc and get removed from the wiki https://github.com/opengisch/QField/wiki/itinerary

**Comment by m-kuhn** [comment]
Do we want to document a feature that needs python command line interaction to be used?

**Comment by mbernasocchi** [comment]
I think we can add an advanced section in the prepare documentation. I'd rather have all in the same place, and get rid of the wiki.
