### ISSUE TITLE
Cannot draw lines or polygons

### ISSUE THREAD

**Issue by HoudGIS** [opengisch/QField-docs#8]
Hi,

After exporting a QGIS project containing un point , line and polygon layers with Qfield Sync, i realized that i cannot draw lines or polygons: when i switch to draw mode, in the select list i get only the points layer.
I can clearly see in the map the line and polygon that i already drawed in QGIS.
My system is Android 4.2.2 system.

Thank you for helping me.

Best

**Comment by m-kuhn** [comment]
I think this is solved for quite some time already. If there is still an issue, please open one at https://github.com/opengisch/QField/issues/
