### ISSUE TITLE
Japanese translation is not reflected to the website

### ISSUE THREAD

**Issue by JinIgarashi** [opengisch/QField-docs#96]
Hi, @m-kuhn, I have translated some case studies' to Japanese language in Transifex. However, they are not reflected yet to the website.

Case studies what I translated were as follows:
- https://qfield.org/docs/ja/case-studies/lulc-mapping-fiji.html
- https://qfield.org/docs/ja/case-studies/vanilla-survey.html

I think normally the translations will be reflected in following day. I don't know why it is not changed yet??

Could you check it please?

**Comment by m-kuhn** [comment]
@JinIgarashi there was an issue with the regular update, this should be fixed now thanks to @suricactus
